apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xrlim97/sample-k8-app.git
    targetRevision: HEAD
    path: hello-app
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-app  
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
